DROP TABLE `myTable`;

CREATE TABLE `myTable` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `usu_nombre` varchar(255) default NULL,
  `usu_password` varchar(255),
  `usu_email` varchar(255) default NULL,
  `usu_foto` varchar(255) default NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `myTable` (`usu_nombre`,`usu_password`,`usu_email`,`usu_foto`) VALUES ("Dieter","7979","Phasellus.nulla@elementumategestas.ca","4.jpg"),("Palmer","3106","sed@velfaucibusid.net","6.jpg"),("Quamar","2731","eu.lacus.Quisque@ullamcorper.edu","3.jpg"),("Mannix","9750","dignissim@facilisisvitae.com","4.jpg"),("Macon","8381","non.cursus@eros.ca","6.jpg"),("Silas","6890","bibendum@risusatfringilla.org","1.jpg"),("Nicholas","6554","luctus@eget.com","9.jpg"),("Macon","5080","tellus.Aenean.egestas@rutrum.co.uk","6.jpg"),("Hakeem","9317","faucibus.ut.nulla@ipsumsodalespurus.org","1.jpg"),("Berk","7941","vulputate.velit.eu@Curabitur.org","3.jpg");
INSERT INTO `myTable` (`usu_nombre`,`usu_password`,`usu_email`,`usu_foto`) VALUES ("Kenyon","3398","nonummy.ut.molestie@eu.net","1.jpg"),("Baxter","1324","sit@erat.net","1.jpg"),("Ferris","7766","magna@nulla.net","4.jpg"),("Ray","6347","ornare.elit.elit@Nuncquisarcu.ca","5.jpg"),("Abel","4535","nisi@nisi.edu","7.jpg"),("Channing","3266","egestas.Duis@leoelementumsem.org","5.jpg"),("Kareem","3035","non.dapibus.rutrum@tempus.com","4.jpg"),("Adrian","2958","volutpat.ornare@turpisNulla.com","10.jpg"),("Xavier","9526","ac@Nullamscelerisque.edu","7.jpg"),("Josiah","2778","turpis@Ut.co.uk","1.jpg");
INSERT INTO `myTable` (`usu_nombre`,`usu_password`,`usu_email`,`usu_foto`) VALUES ("Davis","1157","quis.tristique.ac@nonummyultricies.org","4.jpg"),("Noah","4907","eget@feugiat.edu","5.jpg"),("Ryder","3382","euismod.est.arcu@vehiculaetrutrum.net","9.jpg"),("Ignatius","3815","non.hendrerit@Crasconvallis.co.uk","4.jpg"),("Ezekiel","3776","Vivamus.nisi.Mauris@tincidunt.org","9.jpg"),("Leroy","6424","Integer.in.magna@mattis.edu","5.jpg"),("Nicholas","1218","a@Donecelementumlorem.ca","3.jpg"),("Anthony","2744","Etiam@elementumsemvitae.ca","10.jpg"),("Carlos","5145","fringilla.euismod.enim@aliquameuaccumsan.co.uk","4.jpg"),("Todd","4486","Curae@facilisismagnatellus.edu","5.jpg");
INSERT INTO `myTable` (`usu_nombre`,`usu_password`,`usu_email`,`usu_foto`) VALUES ("Berk","3944","eros@temporbibendum.edu","10.jpg"),("Caldwell","7255","Cras@sedhendrerit.edu","1.jpg"),("Jerome","4372","adipiscing@nonquamPellentesque.com","6.jpg"),("Erasmus","6237","malesuada.vel@acrisusMorbi.co.uk","5.jpg"),("Colin","5657","Donec.luctus.aliquet@a.ca","6.jpg"),("Castor","4376","eu.nulla@magnaa.edu","3.jpg"),("Lars","4123","magna.nec.quam@ridiculusmusProin.edu","9.jpg"),("Kirk","7203","pretium@imperdiet.org","9.jpg"),("Hiram","8917","a.enim@et.co.uk","5.jpg"),("John","6191","Sed.neque.Sed@Donecnibh.ca","2.jpg");
INSERT INTO `myTable` (`usu_nombre`,`usu_password`,`usu_email`,`usu_foto`) VALUES ("Brian","8230","Nulla.aliquet.Proin@Cras.co.uk","5.jpg"),("Xavier","1699","ante.Maecenas@enimnonnisi.com","6.jpg"),("Lee","5305","dolor.quam@varius.net","1.jpg"),("Aidan","4180","Sed.auctor.odio@cursusvestibulumMauris.co.uk","1.jpg"),("Wallace","4240","Donec.egestas.Aliquam@tristique.com","1.jpg"),("Julian","7289","nibh.Quisque.nonummy@vestibulumMauris.net","7.jpg"),("Raja","5024","Quisque.porttitor@Donecconsectetuer.org","8.jpg"),("Raphael","7072","eget.metus.In@malesuadamalesuada.com","9.jpg"),("Boris","5057","neque.tellus.imperdiet@erosturpisnon.com","9.jpg"),("Julian","5925","at@egetdictumplacerat.co.uk","6.jpg");
INSERT INTO `myTable` (`usu_nombre`,`usu_password`,`usu_email`,`usu_foto`) VALUES ("Hamish","4919","lacus@enimgravida.org","6.jpg"),("Prescott","8983","et@commodo.net","8.jpg"),("Basil","4745","ipsum.primis@ametfaucibusut.ca","6.jpg"),("Ali","8007","non@estNunc.net","5.jpg"),("Len","2012","pede.nec.ante@sagittislobortismauris.net","6.jpg"),("Slade","7525","nec@sit.ca","7.jpg"),("Asher","9900","mi.Duis.risus@blanditcongueIn.ca","4.jpg"),("Abdul","9302","libero@pedeCrasvulputate.co.uk","4.jpg"),("Hamilton","5037","lectus.Nullam@Aenean.ca","4.jpg"),("Axel","4488","sem@nullaCraseu.edu","1.jpg");
INSERT INTO `myTable` (`usu_nombre`,`usu_password`,`usu_email`,`usu_foto`) VALUES ("Davis","2883","venenatis.vel@eratvolutpat.net","7.jpg"),("Hector","9166","augue.malesuada@tristiquepellentesquetellus.org","6.jpg"),("Hunter","5215","mi@ligula.ca","10.jpg"),("Omar","5602","nascetur@massa.org","3.jpg"),("Finn","1982","consectetuer.ipsum.nunc@lacusQuisque.net","5.jpg"),("Alan","1224","malesuada@Crassedleo.org","10.jpg"),("Thaddeus","8974","convallis@aliquetdiamSed.co.uk","7.jpg"),("Josiah","1880","vitae.posuere@aliquamerosturpis.org","5.jpg"),("Fletcher","3163","sodales.nisi@tempor.net","6.jpg"),("Daquan","3925","non@neccursusa.edu","1.jpg");
INSERT INTO `myTable` (`usu_nombre`,`usu_password`,`usu_email`,`usu_foto`) VALUES ("Cooper","5896","risus@egestasDuis.edu","7.jpg"),("Griffin","4543","ullamcorper.Duis.at@atarcu.com","3.jpg"),("Clayton","8496","aliquam.iaculis@ipsum.co.uk","2.jpg"),("Prescott","1532","ac@urnaNuncquis.com","4.jpg"),("Anthony","3546","ornare.egestas@ipsumnunc.ca","10.jpg"),("Dustin","1424","arcu@ipsumprimis.co.uk","7.jpg"),("Tad","8034","quam.vel@ullamcorperDuis.com","2.jpg"),("Chandler","2273","elit.a@tempus.org","5.jpg"),("Jeremy","4288","vitae.erat@eget.org","4.jpg"),("Lester","1982","Aenean.eget.metus@velpedeblandit.edu","2.jpg");
INSERT INTO `myTable` (`usu_nombre`,`usu_password`,`usu_email`,`usu_foto`) VALUES ("Dennis","1988","facilisis.non@pretiumet.edu","4.jpg"),("Tiger","1176","aliquet@auctorullamcorper.org","5.jpg"),("Erich","5001","facilisis.Suspendisse@bibendum.org","1.jpg"),("Rudyard","8112","eu.erat@Integer.net","7.jpg"),("Calvin","5338","imperdiet@dolor.edu","1.jpg"),("Evan","1279","Cras@tellusNunclectus.com","1.jpg"),("Kuame","4842","In.condimentum@risusDonecnibh.net","9.jpg"),("Kenneth","6389","quis@justo.net","7.jpg"),("Honorato","9733","eu.tellus.Phasellus@mauriserat.edu","7.jpg"),("Gareth","1823","Integer.vulputate@sem.com","4.jpg");
INSERT INTO `myTable` (`usu_nombre`,`usu_password`,`usu_email`,`usu_foto`) VALUES ("Preston","1541","in.consectetuer.ipsum@Integertincidunt.co.uk","1.jpg"),("Jared","4689","euismod@mi.edu","9.jpg"),("Quentin","9908","ridiculus.mus@sitamet.co.uk","5.jpg"),("Chandler","6372","quam@in.net","2.jpg"),("Cadman","2918","Sed@semperrutrumFusce.net","2.jpg"),("Nasim","6702","leo.in.lobortis@massaQuisque.ca","2.jpg"),("Craig","9598","libero.et.tristique@sem.edu","2.jpg"),("Donovan","7026","fermentum.metus.Aenean@Nulla.co.uk","5.jpg"),("Edward","8735","Integer@pedeCrasvulputate.com","1.jpg"),("Erich","3897","purus.accumsan@arcu.co.uk","4.jpg");
